# Generated by Django 5.1.4 on 2024-12-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='premium',
            new_name='is_premium',
        ),
    ]
