# Generated by Django 5.1.4 on 2024-12-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_folder_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(verbose_name='Link Description'),
        ),
    ]
