# Generated by Django 5.1.4 on 2024-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_rename_name_folder_title_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, verbose_name='Link Description'),
        ),
    ]
